### ISSUE TITLE
To decide icons for Coins

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#155]
**Todo icons for coins** 

Task Checklist 

- [x] 1.We can Determine Icons for Coins:
Approach : What should the icons for coins be?

- [x] 2.Can Create an image initial ticker for coin.
Approach :Select Coin Images:

3.Integrate 10-12 coin images into the app.
Approach : Make images as Default 

4. Irish Wallet uses image from the Display Photo so can consider that too.

- [x] UX Changes major change :

Consider UX changes as the last option and create something new by our own.
