### ISSUE TITLE
To-Do tasks

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcoin-tribe#80]
- [x] Handle keyboardShouldPersistTaps
- [x] Shadow for cards
- [x] check height of Asset card
- [x] Tab bar issues (tab label is in caps(ASSETS) it's in capitalized (Assets), alignment ) 
- [x] font size issue in IOS platform
